"""
Drone RL Lab — Hover Backend (gym-pybullet-drones)
====================================================
Config-driven training for the HoverAviary environment using SB3 PPO.

Usage:
    python train.py configs/exp_006.yaml        # via dispatcher (preferred)
    python train_hover.py configs/exp_006.yaml   # direct call

Linux Claude: create a new YAML config for each experiment.
Do NOT edit this file unless adding new infrastructure.
"""

import os
import sys
import csv
import json
import time
from datetime import datetime
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.callbacks import EvalCallback, BaseCallback
from stable_baselines3.common.evaluation import evaluate_policy

from gym_pybullet_drones.envs.HoverAviary import HoverAviary
from gym_pybullet_drones.utils.enums import ObservationType, ActionType

# PyYAML — install with: pip install pyyaml
try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(1)


# =============================================================================
# CONFIG LOADING
# =============================================================================

def load_config(config_path: str) -> dict:
    """Load experiment config from a YAML file."""
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    required = ["name", "hypothesis", "reward_code", "ppo"]
    for field in required:
        if field not in config:
            raise ValueError(f"Config missing required field: {field}")

    config.setdefault("budget_seconds", 180)
    config.setdefault("backend", "hover")
    return config


# =============================================================================
# CUSTOM ENVIRONMENT — reward function loaded from config
# =============================================================================

def make_hover_aviary_class(reward_code: str):
    """
    Dynamically create a CustomHoverAviary class with the given reward code.

    The reward_code string has access to:
      - self: the environment instance
      - state: drone state vector (position, orientation, velocity, etc.)
      - np: numpy
      - dist: distance from target (pre-computed convenience variable)

    Example reward_code:
      dist = np.linalg.norm(self.TARGET_POS_CUSTOM - state[0:3])
      return max(0, 2 - dist**4)
    """
    # Process reward code: convert final "return X" to "__return__ = X"
    reward_lines = reward_code.strip().split("\n")
    for i in range(len(reward_lines) - 1, -1, -1):
        stripped = reward_lines[i].strip()
        if stripped.startswith("return "):
            reward_lines[i] = reward_lines[i].replace("return ", "__return__ = ", 1)
            break

    processed_code = "\n".join(reward_lines)

    class CustomHoverAviary(HoverAviary):
        TARGET_POS_CUSTOM = np.array([0.0, 0.0, 1.0])

        def _computeReward(self):
            state = self._getDroneStateVector(0)
            dist = np.linalg.norm(self.TARGET_POS_CUSTOM - state[0:3])
            local_vars = {
                "self": self, "state": state, "dist": dist,
                "np": np, "max": max, "min": min, "abs": abs,
                "__return__": 0.0,
            }
            exec(processed_code, local_vars)
            return local_vars["__return__"]

    return CustomHoverAviary


# =============================================================================
# CALLBACKS
# =============================================================================

class TimeBudgetCallback(BaseCallback):
    """Stops training when the wall-clock budget is exceeded."""

    def __init__(self, budget_seconds: int, verbose: int = 0):
        super().__init__(verbose)
        self.budget_seconds = budget_seconds
        self.start_time: float = 0.0

    def _on_training_start(self) -> None:
        self.start_time = time.time()

    def _on_step(self) -> bool:
        elapsed = time.time() - self.start_time
        if elapsed > self.budget_seconds:
            print(f"\n[TimeBudget] {self.budget_seconds}s elapsed — stopping training.")
            return False
        return True


class StepLoggerCallback(BaseCallback):
    """
    Logs per-step metrics during training.
    Records: timestep, distance, velocity, z_pos, episode number.
    Writes to a CSV file at end of training.
    """

    def __init__(self, log_path: str, verbose: int = 0):
        super().__init__(verbose)
        self.log_path = log_path
        self.rows = []
        self.episode_count = 0
        # Log every Nth step to keep file size reasonable
        self.log_every = 10

    def _on_step(self) -> bool:
        if self.num_timesteps % self.log_every != 0:
            return True

        try:
            base_env = self.training_env.envs[0].unwrapped
            state = base_env._getDroneStateVector(0)
            pos = state[0:3]
            vel = state[10:13]
            target = np.array([0.0, 0.0, 1.0])

            self.rows.append({
                "timestep": self.num_timesteps,
                "distance": round(float(np.linalg.norm(target - pos)), 6),
                "velocity": round(float(np.linalg.norm(vel)), 6),
                "z_pos": round(float(pos[2]), 6),
                "episode": self.episode_count,
            })

            dones = self.locals.get("dones", [False])
            if any(dones):
                self.episode_count += 1

        except Exception:
            pass  # Don't crash training if logging fails

        return True

    def _on_training_end(self) -> None:
        self._save()

    def _save(self):
        if not self.rows:
            return
        with open(self.log_path, "w", newline="") as f:
            writer = csv.DictWriter(
                f, fieldnames=["timestep", "distance", "velocity", "z_pos", "episode"]
            )
            writer.writeheader()
            writer.writerows(self.rows)
        print(f"[StepLogger] Wrote {len(self.rows)} rows to {self.log_path}")


# =============================================================================
# MAIN TRAINING LOOP
# =============================================================================

def run(config_path: str):
    config = load_config(config_path)

    name = config["name"]
    hypothesis = config["hypothesis"]
    budget = config["budget_seconds"]
    ppo_kwargs = config["ppo"]
    reward_code = config["reward_code"]

    # ── Paths ─────────────────────────────────────────────────────────────────
    lab_dir = os.path.dirname(os.path.abspath(__file__))
    results_dir = os.path.join(lab_dir, "results", name)
    os.makedirs(results_dir, exist_ok=True)

    # Copy config to results dir for reproducibility
    import shutil
    shutil.copy2(config_path, os.path.join(results_dir, "config.yaml"))

    print(f"\n{'='*65}")
    print(f"  EXPERIMENT: {name}")
    print(f"  HYPOTHESIS: {hypothesis}")
    print(f"  BUDGET:     {budget}s")
    print(f"  CONFIG:     {config_path}")
    print(f"  OUTPUT:     {results_dir}")
    print(f"{'='*65}\n")

    # ── Build environment class from reward code ──────────────────────────────
    CustomHoverAviary = make_hover_aviary_class(reward_code)

    env_kwargs = dict(obs=ObservationType.KIN, act=ActionType.ONE_D_RPM)
    train_env = make_vec_env(CustomHoverAviary, env_kwargs=env_kwargs,
                             n_envs=1, seed=0)
    eval_env = CustomHoverAviary(**env_kwargs)

    print(f"[INFO] Action space:      {train_env.action_space}")
    print(f"[INFO] Observation space: {train_env.observation_space}")
    print(f"[INFO] Reward code:\n{reward_code}\n")

    # ── Model ─────────────────────────────────────────────────────────────────
    model = PPO("MlpPolicy", train_env, verbose=1, **ppo_kwargs)

    # ── Callbacks ─────────────────────────────────────────────────────────────
    time_cb = TimeBudgetCallback(budget_seconds=budget)
    eval_cb = EvalCallback(
        eval_env,
        verbose=1,
        best_model_save_path=results_dir,
        log_path=results_dir,
        eval_freq=1000,
        deterministic=True,
        render=False,
    )
    step_log_path = os.path.join(results_dir, "steps.csv")
    step_cb = StepLoggerCallback(log_path=step_log_path)

    # ── Train ─────────────────────────────────────────────────────────────────
    wall_start = time.time()
    model.learn(
        total_timesteps=int(1e8),
        callback=[time_cb, eval_cb, step_cb],
        log_interval=100,
    )
    elapsed = time.time() - wall_start

    # ── Evaluate best model ───────────────────────────────────────────────────
    best_model_path = os.path.join(results_dir, "best_model.zip")
    if os.path.exists(best_model_path):
        best_model = PPO.load(best_model_path)
        mean_reward, std_reward = evaluate_policy(
            best_model, eval_env, n_eval_episodes=10
        )
    else:
        print("[WARN] No best_model.zip found — using final model for eval.")
        mean_reward, std_reward = evaluate_policy(
            model, eval_env, n_eval_episodes=10
        )

    train_env.close()
    eval_env.close()

    # ── Save metrics ──────────────────────────────────────────────────────────
    metrics = {
        "experiment": name,
        "backend": "hover",
        "hypothesis": hypothesis,
        "config_file": os.path.basename(config_path),
        "timestamp": datetime.now().isoformat(),
        "elapsed_seconds": round(elapsed, 1),
        "mean_reward": round(float(mean_reward), 3),
        "std_reward": round(float(std_reward), 3),
        "timesteps_trained": int(model.num_timesteps),
        "ppo_kwargs": ppo_kwargs,
        "reward_code": reward_code.strip(),
    }

    metrics_path = os.path.join(results_dir, "metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"\n[Saved] {metrics_path}")

    # ── Print summary ─────────────────────────────────────────────────────────
    print(f"\n{'='*65}")
    print(f"  RESULTS")
    print(f"  mean_reward  = {mean_reward:.3f} ± {std_reward:.3f}")
    print(f"  timesteps    = {model.num_timesteps:,}")
    print(f"  wall time    = {elapsed:.1f}s")
    print(f"{'='*65}\n")

    # ── Write outbox file ─────────────────────────────────────────────────────
    outbox_dir = os.path.join(lab_dir, "outbox")
    os.makedirs(outbox_dir, exist_ok=True)
    outbox_path = os.path.join(outbox_dir, f"{name}.md")
    with open(outbox_path, "w") as f:
        f.write(f"# {name} — Results\n\n")
        f.write(f"**Hypothesis:** {hypothesis}\n\n")
        f.write(f"| Metric | Value |\n|--------|-------|\n")
        f.write(f"| mean_reward | {mean_reward:.3f} ± {std_reward:.3f} |\n")
        f.write(f"| timesteps_trained | {model.num_timesteps:,} |\n")
        f.write(f"| wall_time | {elapsed:.1f}s |\n\n")
        f.write(f"*(Linux Claude: write full analysis to "
                f"`results/{name}/EXPERIMENT.md`, then update this file.)*\n")
    print(f"[Updated] {outbox_path}")

    print(f"\nNext steps for Linux Claude:")
    print(f"  1. Write results/{name}/EXPERIMENT.md")
    print(f"  2. git add -A && git commit -m '{name}: <summary>'")
    print(f"  3. Update outbox/{name}.md with your analysis\n")

    return metrics


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python train_hover.py configs/exp_NNN.yaml")
        print("\nAvailable configs:")
        configs_dir = os.path.join(os.path.dirname(__file__), "configs")
        if os.path.isdir(configs_dir):
            for f in sorted(os.listdir(configs_dir)):
                if f.endswith(".yaml"):
                    print(f"  python train_hover.py configs/{f}")
        sys.exit(1)

    run(sys.argv[1])
